In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.metrics as mt
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import RandomizedSearchCV
import joblib
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

In [2]:
model_data = pd.read_csv("data.csv")

X = model_data.iloc[:, :4]
X_names = X.columns
y = model_data["label_ko"]

X_past = X[y.notna()]
y_past = y[y.notna()]

sss = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)

for train_index, test_index in sss.split(X_past, y_past):
    X_train, X_test = X_past.iloc[train_index,], X_past.iloc[test_index,]
    y_train, y_test = y_past[train_index], y_past[test_index]
    
sc = StandardScaler()
sc.fit(X_train)
X_train_std = sc.transform(X_train)
X_past_std = sc.transform(X_past)
X_test_std = sc.transform(X_test)

In [3]:
SVM = SVC(kernel = 'rbf', C = 10.0, gamma = 5, random_state = 0)
svm_scores = cross_val_score(SVM, X_train_std, y_train, cv = 5)
print("accuracy score mean: ", svm_scores.mean())

accuracy score mean:  0.8232977806507218


In [4]:
SVM.fit(X_train_std, y_train)
SVM.score(X_train_std, y_train)

0.9362170087976539

In [5]:
y_pred = SVM.predict(X_test_std)
mt.accuracy_score(y_test, y_pred)

0.8152492668621701

In [6]:
y_test_pred = SVM.predict(X_test_std)
cm1= confusion_matrix(y_test, y_test_pred, labels=["up","neutral","down"])
print("\n<Confusion matrix>")
print("(of test)")
print("up","neutral","down")
print(cm1)


<Confusion matrix>
(of test)
up neutral down
[[ 79  16   7]
 [  9  67  16]
 [  3  12 132]]


In [7]:
cm2= confusion_matrix(y_past, SVM.predict(X_past_std), labels=["up","neutral","down"])
print("(of all)")
print("up","neutral","down")
print(cm2)

(of all)
up neutral down
[[459  26  23]
 [ 21 395  46]
 [ 11  23 701]]
